apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
{{- if ne .Values.ingress.tls.source "secret" }}
    certmanager.k8s.io/issuer: {{ template "rancher.fullname" . }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.hostname }}  # hostname to access rancher server
    http:
      paths:
      - backend:
          serviceName: {{ template "rancher.fullname" . }}
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: tls-rancher-ingress

